name: mhudart_common
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  built_collection: ^5.1.1
  kt_dart: ^1.0.0
  logging: ^1.1.1
  protobuf: ^2.1.0
  retry: ^3.1.0
  rxdart: ^0.27.7

dev_dependencies:
